# Generated by Django 3.1.7 on 2021-03-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
    ]
